name: Auto Update HTML Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy HTML to other devices
        run: |
          scp -r * user--49@192.168.1.74:/home/user--49/test/deployfolder1
